# Generated by Django 2.2 on 2019-06-13 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20190613_1327'),
        ('shopping_cart', '0005_auto_20180609_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='downloadable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Product'),
        ),
    ]
