# Generated by Django 2.2 on 2019-06-13 10:27

import django.core.files.storage
from django.db import migrations, models
import products.models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='download',
            field=models.FileField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\cipher\\work\\static_cdn\\protected'), upload_to=products.models.download_loc),
        ),
    ]
